name: Merge dev PR to alpha branch

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  mergePr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Merge into branch alpha
        run: |
          git checkout ${{ github.event.pull_request.head.ref }}
          git branch
          git log --oneline
          echo ${{ github.event.pull_request.head.ref }}
          # git merge --no-ff ${{ github.event.pull_request.head.ref }} -m "Merge pull request into Alpha"
        env:
          TARGET_BRANCH: alpha
